# Jekyll Configuration File.
# https://jekyllrb.com/docs/configuration/
---
#baseurl: https://violetrollergirl.com
baseurl: "" # Comment the above line and uncomment this to test the website locally

# Basic site and authorship information.
title: Violet Rollergirl
subtitle: Bubbly trans GFE companion
author: &author Violet Rollergirl
description: >-
  Brilliant, bubbly, and beautifully nerdy, Violet is your confident,
  kind, trans girlfriend experience where sophistication meets genuine
  sparkle.

# Contact details and templates.
booking:
  subject: Booking inquiry
  template_txt: |-
    Hi Violet, my name is __. I found you via your website and would like to book an INCALL/OUTCALL on __ for __ hours in CITY. Thanks!
  template: "" # TODO: A more complete text template.
contact:
  email: violetrollergirl@protonmail.com
  signal:
    url: https://signal.me/#eu/hXeV89EMDRGessR7BjUl9x0sRr4XA6LoQ_I9YIT--TRduWmPwy9H7bPWLFx6M6xw
    username: VioletRollergirl.69
  sms:
    tel: "+19295547784"
    vanity: "+1 929-5-KISS-VI"
  whatsapp: "+19174407408"
  xmpp:
    jid: violet@violetrollergirl.snikket.chat

defaults:
  - values:
      layout: page
  - scope:
      path: "images/gallery/fulls"
    values:
      gallery_image: true
  - scope:
      path: "images/gallery/fulls/020-cyberpunk-kneeling-bondage-wall-Violet-Rollergirl-9108_124341~2.jpg"
    values:
      position: top
  - scope:
      path: "images/gallery/fulls/black-and-white-polka-dots-on-rattan-chair.jpg"
    values:
      position: top
  - scope:
     path: "images/gallery/fulls/cutie-in-bay-windows.jpg"
    values:
      position: top
  - scope:
      path: "images/gallery/fulls/hello-kitty-panties.jpg"
    values:
      position: top
  - scope:
      type: posts
    values:
      author: *author
      layout: post

  # FAQ groups.
  - scope:
      path: ""
      type: faq
    values:
      layout: faq-page
  - scope:
      path: "_faq/about-me"
    values:
      group_name: About me
  - scope:
      path: "_faq/about-you"
    values:
      group_name: About you
  - scope:
      path: "_faq/meetings"
    values:
      group_name: Meetings
  - scope:
      path: "_faq/screening"
    values:
      group_name: Screening
  - scope:
      path: "_faq/services"
    values:
      group_name: Services

collections:
  faq:
    output: true
    permalink: /:collection/:path/
  posts:
    permalink: /blog/:year/:month/:day/:title/
  testimonials:

# Gallery.
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
#exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
